language: node_js
node_js:
  - 12

addons:
  sonarcloud:
    organization: "gestiontareas"
    token: "7d1ea67997fbac456c84a081d0af7096e8645541"
     
install:
  - npm install

script:
  - npm run build

deploy: &heroku
        provider: heroku
        app: siget-equipo2-cliente
        api_key: 18562f60-1231-4327-8b42-88518f1e5dde
        on:
          branch: master

server:
        port: $PORT
